version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rinkudesu
      POSTGRES_PASSWORD: your_very_safe_password_here
      POSTGRES_DB: rinkudesu
    volumes:
      - ./tags-postgres:/var/lib/postgresql/data

  rinkudesu-tags:
    image: ghcr.io/rinkudesu/rinkudesu-tags:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - postgres
    environment:
      TAGS_DB: "postgres://rinkudesu:your_very_safe_password_here@postgres:5432/rinkudesu"
      TAGS_LOG-LEVEL: "info"
      GIN_MODE: "release"
      TAGS_AUTHORITY: "rinkudesu"