version: '3'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: rinkudesu
      POSTGRES_PASSWORD: rinkudesu
      POSTGRES_DB: rinkudesu
    volumes:
      - ./tags-postgres:/var/lib/postgresql/data
  rinkudesu-tags:
    image: ghcr.io/rinkudesu/rinkudesu-tags:latest
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      TAGS_DB: "postgres://rinkudesu:rinkudesu@postgres:5432/rinkudesu"
      TAGS_LOG-LEVEL: "debug"
      TAGS_AUTHORITY: "rinkudesu"
