// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Repositories

import (
	"github.com/google/wire"
	"rinkudesu-tags/Data"
)

// Injectors from repositores_wire.go:

func CreateLinksRepository(dbConnection Data.DbConnector) *LinksRepository {
	linksRepository := NewLinksRepository(dbConnection)
	return linksRepository
}

func CreateTagsRepository(dbConnection Data.DbConnector) *TagsRepository {
	tagQueryExecutable := NewTagQueryExecutor(dbConnection)
	tagsRepository := NewTagsRepository(tagQueryExecutable)
	return tagsRepository
}

func CreateLinkTagsRepository(dbConnection Data.DbConnector) *LinkTagsRepository {
	linkTagsRepository := NewLinkTagsRepository(dbConnection)
	return linkTagsRepository
}

// repositores_wire.go:

var (
	LinkRepositorySet     = wire.NewSet(NewLinksRepository)
	TagsRepositorySet     = wire.NewSet(NewTagsRepository, NewTagQueryExecutor)
	LinkTagsRepositorySet = wire.NewSet(NewLinkTagsRepository)
)
