// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Repositories

import (
	"github.com/google/wire"
	"rinkudesu-tags/Services"
)

// Injectors from repositores_wire.go:

func CreateLinksRepository(state *Services.GlobalState) *LinksRepository {
	linksRepository := NewLinksRepository(state)
	return linksRepository
}

func CreateTagsRepository(state *Services.GlobalState) *TagsRepository {
	tagsRepository := NewTagsRepository(state)
	return tagsRepository
}

func CreateLinkTagsRepository(state *Services.GlobalState) *LinkTagsRepository {
	linkTagsRepository := NewLinkTagsRepository(state)
	return linkTagsRepository
}

// repositores_wire.go:

var (
	LinkRepositorySet     = wire.NewSet(NewLinksRepository)
	TagsRepositorySet     = wire.NewSet(NewTagsRepository)
	LinkTagsRepositorySet = wire.NewSet(NewLinkTagsRepository)

	AllRepositoriesSet = wire.NewSet(LinkRepositorySet, TagsRepositorySet, LinkTagsRepositorySet)
)
