// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/google/wire"
	"rinkudesu-tags/repositories"
	"rinkudesu-tags/services"
)

// Injectors from controllers_wire.go:

func CreateLinksController(state *services.GlobalState) *LinksController {
	linksRepository := repositories.NewLinksRepository(state)
	linksController := NewLinksController(linksRepository)
	return linksController
}

func CreateTagsController(state *services.GlobalState) *TagsController {
	tagsRepository := repositories.NewTagsRepository(state)
	tagsController := NewTagsController(tagsRepository)
	return tagsController
}

func CreateLinkTagsController(state *services.GlobalState) *LinkTagsController {
	linkTagsRepository := repositories.NewLinkTagsRepository(state)
	linksRepository := repositories.NewLinksRepository(state)
	tagsRepository := repositories.NewTagsRepository(state)
	linkTagsController := NewLinkTagsController(linkTagsRepository, linksRepository, tagsRepository)
	return linkTagsController
}

// controllers_wire.go:

var (
	LinksControllerSet    = wire.NewSet(NewLinksController, repositories.LinkRepositorySet)
	TagsControllerSet     = wire.NewSet(NewTagsController, repositories.TagsRepositorySet)
	LinkTagsControllerSet = wire.NewSet(NewLinkTagsController, repositories.LinkTagsRepositorySet, repositories.LinkRepositorySet, repositories.TagsRepositorySet)
)
