// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/google/wire"
)

// Injectors from services_wire.go:

func CreateHealthcheck(state *GlobalState) *Healthcheck {
	healthcheck := NewHealthcheck(state)
	return healthcheck
}

// services_wire.go:

var (
	HealthcheckSet = wire.NewSet(NewHealthcheck)
)
