// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package MessageHandlers

import (
	"github.com/google/wire"
	"rinkudesu-tags/Repositories"
	"rinkudesu-tags/Services"
)

// Injectors from messages_wire.go:

func CreateUserDeletedHandler(state *Services.GlobalState) *UserDeletedHandler {
	linksRepository := Repositories.NewLinksRepository(state)
	tagsRepository := Repositories.NewTagsRepository(state)
	linkTagsRepository := Repositories.NewLinkTagsRepository(state)
	userDeletedHandler := NewUserDeletedHandler(linksRepository, tagsRepository, linkTagsRepository)
	return userDeletedHandler
}

// messages_wire.go:

var (
	UserDeletedHandlerSet = wire.NewSet(NewUserDeletedHandler, Repositories.AllRepositoriesSet)
)
