// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package message_handlers

import (
	"github.com/google/wire"
	"rinkudesu-tags/repositories"
	"rinkudesu-tags/services"
)

// Injectors from messages_wire.go:

func CreateUserDeletedHandler(state *services.GlobalState) *UserDeletedHandler {
	linksRepository := repositories.NewLinksRepository(state)
	tagsRepository := repositories.NewTagsRepository(state)
	linkTagsRepository := repositories.NewLinkTagsRepository(state)
	userDeletedHandler := NewUserDeletedHandler(linksRepository, tagsRepository, linkTagsRepository)
	return userDeletedHandler
}

// messages_wire.go:

var (
	UserDeletedHandlerSet = wire.NewSet(NewUserDeletedHandler, repositories.AllRepositoriesSet)
)
